# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Make Production release"
  lane :distribute_production do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    release = firebase_app_distribution(
      app: "1:498736246572:android:02cac52a622ea05aa30689",
      firebase_cli_token:"",
      android_artifact_type:"APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk"
      testers: "mobiledevelopment2002@gmail.com",
      release_notes: "Lots of amazing new features to test out!"
  )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :distribute_development do
    sh "flutter clean"
    sh "flutter build apk --release --flavor development --target lib/main_development.dart --no-tree-shake-icons"    
    release = firebase_app_distribution(
      app: "1:498736246572:android:02cac52a622ea05aa30689",
      firebase_cli_token:"",
      android_artifact_type:"APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-development-release.apk"
      testers: "mobiledevelopment2002@gmail.com",
      release_notes: "Lots of amazing new features to test out!"
  )
  end
end
