# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Make Production release"
  lane :distribute_production do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    release = firebase_app_distribution(
      app: ENV['PRODUCTION_APP_ID'],
      firebase_cli_token:ENV['FIREBASE_CLI_TOKEN'],
      android_artifact_type:"APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mobiledevelopment2002@gmail.com",
      release_notes: "Lots of amazing new features to test out!"
  )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :distribute_development do
    sh "flutter clean"
    sh "flutter build apk --release --flavor development --target lib/main_development.dart --no-tree-shake-icons"    
    release = firebase_app_distribution(
      app: ENV['DEVELOPMENT_APP_ID'],
      firebase_cli_token:ENV['FIREBASE_CLI_TOKEN'],
      android_artifact_type:"APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-development-release.apk",
      testers: "mobiledevelopment2002@gmail.com",
      release_notes: "Lots of amazing new features to test out!"
  )
  end

  desc "Demo using different .env files print sample"
  lane :sampleTest do
      # sampleTest
      print "Current app Id = #{ENV['FIREBASE_CLI_TOKEN']} and api key = #{ENV['PRODUCTION_APP_ID']}"
      # You can add other commands here
  end 

end
